### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Crusfire63** [CleverNucleus/DataAttributes#8]
I have that when a want play with playerex and dataattribute :

`[22:21:43] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[22:21:44] [main/INFO]: Loading 147 mods:
	- advancednetherite 1.4.1-1.18.2
	- ambientenvironment 7.0+18
	- appleskin 2.3.0+mc1.18.1
	- architectury 4.0.30
	- armorpointspp 3.0.0-beta4
	- autoconfig1u 3.4.0 via rpgstats
	- awesomedungeon 2.0.5
	- betterbiomeblend 1.18.2-1.3.3-fabric
	- betterf3 1.2.3
	- blue_endless_jankson 1.2.1 via jankson
	- caffeineconfig 1.0.0 via sodium-extra
	- cardinal-components 4.1.4
	- cardinal-components-base 4.1.4 via cardinal-components
	- cardinal-components-block 4.1.4 via cardinal-components
	- cardinal-components-chunk 4.1.4 via cardinal-components
	- cardinal-components-entity 4.1.4 via cardinal-components
	- cardinal-components-item 4.1.4 via cardinal-components
	- cardinal-components-level 4.1.4 via cardinal-components
	- cardinal-components-scoreboard 4.1.4 via cardinal-components
	- cardinal-components-world 4.1.4 via cardinal-components
	- charmonium 4.0.0
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-scissors-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- clumps 8.0.0+7
	- collective-fabric 4.24
	- com_electronwill_night-config_core 3.6.3 via easymagic
	- com_electronwill_night-config_toml 3.6.3 via easymagic
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_moandjiezana_toml_toml4j 0.7.2 via charmonium
	- com_typesafe_config 1.4.1 via croptopia
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- continuity 1.1.0+1.18.2
	- creeperoverhaul 1.3.0
	- croptopia 1.8.1
	- dataattributes 1.1.5
	- doubledoors-fabric 3.3
	- dynamicsoundfilters 1.3.0+1.18.2
	- easymagic 3.3.0
	- enhanced_attack_indicator 1.0.2+1.18
	- fabric 0.47.10+1.18.2
	- fabric-api-base 0.4.3+d7c144a8d2 via cardinal-components
	- fabric-api-lookup-api-v1 1.5.6+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.2+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.11+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.8+d7c144a860 via fabric
	- fabric-commands-v0 0.2.7+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.20+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.1+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.10+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.16+2540745460 via fabric
	- fabric-entity-events-v1 1.4.7+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.18+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.12+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.12+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.2+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.9+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.11+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.9+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.1+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.10+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.3+d1027f7d60 via fabric
	- fabric-models-v0 0.3.5+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.20+d882b91560 via fabric
	- fabric-networking-v0 0.3.7+b4f4f6cdd2 via cardinal-components
	- fabric-object-builder-api-v1 2.0.2+34b2a0ce60 via fabric
	- fabric-particles-v1 0.2.11+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.7+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.12+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.16+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.6+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.1+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.17+801ec85b60 via fabric
	- fabric-screen-api-v1 1.0.9+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.13+d7c144a860 via fabric
	- fabric-textures-v0 1.0.11+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.13+cca23f9360 via fabric
	- fabricloader 0.13.3
	- fallingleaves 1.10.0+1.18.2
	- fallingtree 0.0.1-dev
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- fiber 0.23.0-2 via armorpointspp
	- forgeconfigapiport 3.2.0
	- fpsreducer 1.25-mc1.18
	- geckolib3 3.0.35
	- goosik-config 0.2.0 via visuality
	- guardvillagers 1.18.2-1.0.8
	- iceberg 1.0.38
	- indium 1.0.2+mc1.18.2
	- inventoryhud 3.4.2
	- inventoryprofilesnext 1.3.5
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.2.1-rc2-0cc372f0-dirty
	- itemscroller 0.16.0
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kirin 1.10.0 via presencefootsteps
	- krypton 0.1.7
	- lambdynlights 2.1.0+1.17
	- legendarytooltips 1.2.4
	- libgui 5.3.1+1.18 via rpgstats
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.3
	- lithium 0.7.9
	- malilib 0.12.0
	- minecraft 1.18.2
	- modmenu 3.1.0
	- net_objecthunter_exp4j 0.4.8 via playerex
	- opc 0.0.1 via playerex
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- placeholder-api 1.1.3+1.17.1 via playerex
	- playerex 3.1.4
	- presencefootsteps 1.5.0
	- pride 1.1.0+1.17 via lambdynlights
	- puzzleslib 3.3.1
	- reeses-sodium-options 1.4.1
	- roughlyenoughitems 8.0.442
	- rpgstats 4.3.6+1.18.2
	- seedfix 1.0.1
	- server_translations_api 1.4.10+1.18.2 via rpgstats
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.1
	- spark 1.8.14
	- spruceui 3.3.0+1.17 via lambdynlights
	- starterkit-fabric 3.1
	- tinyskeletons 3.2.0
	- tlcosmetica 0.4.0 via visuality
	- veinmining 0.0.12-1.18.2
	- visuality 0.4.2
	- xaerominimap 22.3.0
	- xaeroworldmap 1.20.3.1
[22:21:44] [main/WARN]: Mod `xaeroworldmap` (1.20.3.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[22:21:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/firni/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:21:44] [main/INFO]: Compatibility level set to JAVA_17
[22:21:44] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 1 override(s) found
[22:21:44] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[22:21:44] [main/INFO]: Loaded configuration file for Sodium Extra: 25 options available, 0 override(s) found
[22:21:44] [main/WARN]: Error loading class: link/infra/indium/renderer/render/AbstractQuadRenderer (java.lang.ClassNotFoundException: link/infra/indium/renderer/render/AbstractQuadRenderer)
[22:21:44] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[22:21:44] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[22:21:44] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[22:21:45] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[22:21:45] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[22:21:45] [main/ERROR]: Mixin apply for mod dataattributes failed dataattributes.mixins.json:SimpleRegistryMixin -> net.minecraft.class_2370: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_11107 was not located in the target class net.minecraft.class_2370. Using refmap dataattributes-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_11107 was not located in the target class net.minecraft.class_2370. Using refmap dataattributes-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:153) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[22:21:45] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2370 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2370 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dataattributes.mixins.json:SimpleRegistryMixin] from phase [DEFAULT] in config [dataattributes.mixins.json] from mod [dataattributes] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_11107 was not located in the target class net.minecraft.class_2370. Using refmap dataattributes-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
`

**Comment by CleverNucleus** [comment]
Hi there,
I have not yet updated to Minecraft 1.18.2, which despite being only a minor version, still presents mixin/fabric api incompatibilities with the previous version. 

Timeframe: I have currently paused development due to some unforeseen life events, however I expect to be able to push an update before the end of April. 
Thanks.
