### ISSUE TITLE
Crash when marauder spawns

### ISSUE THREAD

**Issue by gaycomputers** [CleverNucleus/DataAttributes#93]
I have other mods and would like to keep playerex etc. any tips to debug this would be welcome:

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2023-06-24 06:35:23
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "com.github.clevernucleus.dataattributes.mutable.MutableDefaultAttributeContainer.copy(net.minecraft.class_5132$class_5133)" because the return value of "net.minecraft.class_5135.method_26873(net.minecraft.class_1299)" is null
    at com.github.clevernucleus.dataattributes.impl.AttributeManager.getContainer(AttributeManager.java:359)
    at net.minecraft.class_1309.handler$chh000$dataattributes$data_init(class_1309.java:6617)
    at net.minecraft.class_1309.<init>(class_1309.java:259)
    at net.minecraft.class_1308.<init>(class_1308.java:135)
    at net.minecraft.class_1314.<init>(class_1314.java:14)
    at net.minecraft.class_1588.<init>(class_1588.java:31)
    at net.minecraft.class_3732.<init>(class_3732.java:34)
    at net.minecraft.class_3763.<init>(class_3763.java:61)
    at net.minecraft.class_1543.<init>(class_1543.java:25)
    at me.sandbox.entity.MarauderEntity.<init>(MarauderEntity.java:34)
    at net.minecraft.class_1299.method_5883(class_1299.java:487)
    at net.minecraft.class_3769.handler$dld000$illagerexp$spawnMarauder(class_3769.java:2531)
    at net.minecraft.class_3769.method_16575(class_3769.java)
    at net.minecraft.class_3769.method_6445(class_3769.java:90)
    at net.minecraft.class_3218.method_29202(class_3218.java:409)
    at net.minecraft.class_3215.method_14161(class_3215.java:386)
    at net.minecraft.class_3215.method_12127(class_3215.java:323)
    at net.minecraft.class_3218.method_18765(class_3218.java:319)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
    at net.minecraft.class_3176.method_3813(class_3176.java:289)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
    at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
    at com.github.clevernucleus.dataattributes.impl.AttributeManager.getContainer(AttributeManager.java:359)
    at net.minecraft.class_1309.handler$chh000$dataattributes$data_init(class_1309.java:6617)
    at net.minecraft.class_1309.<init>(class_1309.java:259)
    at net.minecraft.class_1308.<init>(class_1308.java:135)
    at net.minecraft.class_1314.<init>(class_1314.java:14)
    at net.minecraft.class_1588.<init>(class_1588.java:31)
    at net.minecraft.class_3732.<init>(class_3732.java:34)
    at net.minecraft.class_3763.<init>(class_3763.java:61)
    at net.minecraft.class_1543.<init>(class_1543.java:25)
    at me.sandbox.entity.MarauderEntity.<init>(MarauderEntity.java:34)
    at net.minecraft.class_1299.method_5883(class_1299.java:487)
    at net.minecraft.class_3769.handler$dld000$illagerexp$spawnMarauder(class_3769.java:2531)
    at net.minecraft.class_3769.method_16575(class_3769.java)
    at net.minecraft.class_3769.method_6445(class_3769.java:90)
    at net.minecraft.class_3218.method_29202(class_3218.java:409)
    at net.minecraft.class_3215.method_14161(class_3215.java:386)
    at net.minecraft.class_3215.method_12127(class_3215.java:323)
    at net.minecraft.class_3218.method_18765(class_3218.java:319)
```

**Comment by CleverNucleus** [comment]
Hi there,
Could I please get the full log in a pastebin or similar?
Thanks.

**Comment by gaycomputers** [comment]
Crash:
https://pastebin.com/qKk44i1S

Log:
https://pastebin.com/S3gAUHab

**Comment by gaycomputers** [comment]
for now I'm removing illager-expansion-rematch, is there a way to fix this error otherwise?

**Comment by CleverNucleus** [comment]
@s0lvent thanks for the logs - I am looking into the issue now.

**Comment by CleverNucleus** [comment]
Fixed with PR to Illager Expansion - available [here](https://github.com/ZekeSmith/Illager-Expansion-Rematch/pull/11).
