### ISSUE TITLE
Unable to login the server{Data length overflow}

### ISSUE THREAD

**Issue by DavidBlackCN** [CleverNucleus/DataAttributes#98]
cilent:
`Internal Exception: io.nettyhandler.codec.DecoderException: javalangndex0ut0fBoundsException: Index 25 out of bounds for length 5` 

server:
> [00:32:12] [Server thread/WARN]: Failed to handle packet for /XXX.XXX
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$$0" is null
	at net.minecraft.class_2519.method_23256(class_2519.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487.method_10582(class_2487.java:231) ~[server-intermediary.jar:?]
	at com.github.clevernucleus.dataattributes.json.AttributeOverrideJson.writeToNbt(AttributeOverrideJson.java:44) ~[dataattributes-1.4.6+1.19.2.jar:?]
	at com.github.clevernucleus.dataattributes.impl.EntityAttributeData.writeToNbt(EntityAttributeData.java:78) ~[dataattributes-1.4.6+1.19.2.jar:?]
	at com.github.clevernucleus.dataattributes.impl.AttributeManager.lambda$toNbt$8(AttributeManager.java:254) ~[dataattributes-1.4.6+1.19.2.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at com.github.clevernucleus.dataattributes.impl.AttributeManager.toNbt(AttributeManager.java:252) ~[dataattributes-1.4.6+1.19.2.jar:?]
	at com.github.clevernucleus.dataattributes.DataAttributes.loginQueryStart(DataAttributes.java:38) ~[dataattributes-1.4.6+1.19.2.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerLoginConnectionEvents.lambda$static$2(ServerLoginConnectionEvents.java:51) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.queryTick(ServerLoginNetworkAddon.java:83) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
	at net.minecraft.class_3248.redirect$dnb000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:562) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bbn000$carpet$modifiedRunLoop(MinecraftServer.java:4385) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[00:32:12] [Netty Play IO Thread #1/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source) ~[netty-transport-4.1.77.Final.jar:?]

I noticed(#24),May the issue I encounter be similar?
I didn't use Authme or proxy server.
I have already tried XLpackets,But it doesn't work.
I have confirmed that the error came from this mod, as the server returned to normal after I deleted this mod.

Minecraft=1.19.2
Fabric=0.14.21
Dataattributes=1.4.6

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate the report. Does this occur with just Data Attributes and Fabric API (and/or PlayerEx if that's what you're using)? 
Thanks.
